apiVersion: 1
datasources:
  - name: Warehouse
    uid: warehouse
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: ${DASHBOARD_DB_USER}
    secureJsonData:
      password: ${DASHBOARD_DB_PASSWORD}
    jsonData:
      database: ${WAREHOUSE_DB_NAME}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
